### ISSUE TITLE
How can I make a chart smaller on large screens?

### ISSUE THREAD

**Issue by songproducer** [overcastsoftware/wagtailcharts#22]
This is article_page.html:
```
 {% include_block page.body %}

{% for block in page.chart %}
        <div class="size-16 py-8">
            {{ block }}
        </div>
{% endfor %}
{% block extra_js %}
        {% render_charts %}
{% endblock %}
```

But the problem is the chart is gigantic.

When I provide a template to override the template for charts - I can successfully constrain the max-width using max-w-xs but

`{{ block.value }}`

in the template prints out:

 StructValue([('chart_type', 'pie'), ('title', 'a pie chart'), ('datasets......

and not the pie chart

**Comment by songproducer** [comment]
This is how I've included the chart in utils/blocks.py

```
class StoryBlock(blocks.StreamBlock):
    section = SectionBlock()
    cta = CTASectionBlock()
    statistics = StatisticSectionBlock()
    image = ImageChooserBlock()
    embed = EmbedBlock(max_width=800, max_height=400, required=False, template="")
    richtext = blocks.RichTextBlock()
    table = TypedTableBlock([
        ('text', blocks.CharBlock()),
        ('numeric', blocks.FloatBlock()),
        ('rich_text', blocks.RichTextBlock()),
        ('image', ImageChooserBlock())
    ], template="components/streamfield/typed_table_block.html")
    chart = ChartBlock(icon = "chart") #, template="components/streamfield/chart.html"

    class Meta:
        template = "components/streamfield/stream_block.html"
```

**Comment by saevarom** [comment]
You are essentially overriding this template: `https://github.com/overcastsoftware/wagtailcharts/blob/main/wagtailcharts/templates/wagtailcharts/blocks/chart_block.html`
Take a look at how that template renders the charts. You really need to render a `<canvas>` element with the proper attributes.

**Comment by songproducer** [comment]
Thanks very much I got it working!
